apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: tbd
  name: opensearch-tbd-sparsom-prometheus
  namespace: tbd
spec:
  project: nav-dev
  integrationType: prometheus
  destinationEndpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733
  sourceServiceName: opensearch-tbd-sparsom